#!/usr/bin/env python3
"""
Step 4: normalizing the grammar of the expanded text.

Steps 1 and 2 insert the glossary expansions in their base (dictionary)
form, so the expanded text contains words that are grammatically wrong in
their context (e.g. "de 7 annus" instead of "de 7 annis"). Step 4 uses the
same multiple-choice setup as steps 2 and 3: every word of the text that
*is* a glossary base form is marked as [[id|word]], the model picks one
form from the word's full paradigm (generated by paradigm.py from the
cleaned Wortstamm/Deklination columns), and the substitution happens
programmatically. Because every choice is validated by a membership test
against the paradigm, the model can fix the inflection but can never
change the word or corrupt the text.

Words that were never abbreviated must not change at all. The expansion
steps only ever replace abbreviations (tokens ending in a period), so
every original word reappears unchanged and in order in the expanded
text; aligning the two texts (inserted_spans) identifies the words the
pipeline inserted, and only those are marked (an original word that is
indistinguishable from an adjacent identical insertion counts as inserted
too, so it can still be normalized). Words still followed by a period are
unexpanded abbreviations and are left alone as well.
"""

import json
import re
from difflib import SequenceMatcher

from multiple_choice import Occurrence, apply_choices, mark_text
from paradigm import entry_forms

WORD = re.compile(r"\b[A-Za-z]+\b")
TOKEN = re.compile(r"[A-Za-z]+\.?")


def inserted_spans(original: str, expanded: str) -> list[tuple[int, int]] | None:
    """
    Character spans (in `expanded`) of the words the expansion steps
    inserted. Every original word (token without a trailing period) must
    reappear unchanged and in order in the expanded text -- the expanded
    tokens that do not take part in this alignment are the insertions.

    Returns None if some original word cannot be matched: the expanded
    text then was not produced by pure abbreviation substitution (e.g. by
    an old full-text-rewrite run) and must not be normalized at all.

    An original word that stands next to an identical insertion (with at
    most other insertions in between) cannot be told apart from it -- the
    alignment could just as well have matched the other one. Both are
    included, so the model may normalize either instead of the safeguard
    protecting the wrong one.
    """
    orig = [(m.group(0), m.start(), m.end()) for m in TOKEN.finditer(original)]
    exp = [(m.group(0), m.start(), m.end()) for m in TOKEN.finditer(expanded)]
    matcher = SequenceMatcher(
        a=[t for t, _, _ in orig], b=[t for t, _, _ in exp], autojunk=False
    )

    matched_orig = [False] * len(orig)
    matched_exp = [False] * len(exp)
    for block in matcher.get_matching_blocks():
        for k in range(block.size):
            matched_orig[block.a + k] = True
            matched_exp[block.b + k] = True

    for (token, _, _), matched in zip(orig, matched_orig):
        if not matched and not token.endswith("."):
            return None

    def word_span(index: int) -> tuple[int, int]:
        token, start, end = exp[index]
        if token.endswith("."):
            end -= 1  # abbreviations kept in the text: span the word only
        return start, end

    spans = set()
    for j, matched in enumerate(matched_exp):
        if matched:
            continue
        spans.add(word_span(j))
        # identical matched neighbours are alignment-ambiguous with the
        # insertion: include them too (see docstring)
        token = exp[j][0]
        for step in (-1, 1):
            i = j + step
            while 0 <= i < len(exp):
                if not matched_exp[i]:
                    i += step  # another insertion does not anchor the alignment
                    continue
                if exp[i][0] != token:
                    break  # a different matched word is a fixed anchor
                spans.add(word_span(i))
                i += step
    return sorted(spans)


def build_lexicon(entries) -> dict[str, set[str]]:
    """
    word -> all acceptable forms, built from (Auflösung, Wortstamm,
    Deklination) triples. Words with unknown morphology and words with a
    single form (fixed words like "et") are left out -- there is nothing
    to choose for them. Lowercase words get a capitalized variant with
    capitalized forms, so sentence-initial occurrences are found too.
    """
    lexicon: dict[str, set[str]] = {}
    for aufloesung, wortstamm, deklination in entries:
        for word, forms in entry_forms(aufloesung, wortstamm, deklination) or []:
            if forms is not None and len(forms) > 1:
                lexicon.setdefault(word, set()).update(forms)
    for word in list(lexicon):
        if word[0].islower():
            capitalized = {form.capitalize() for form in lexicon[word]}
            lexicon.setdefault(word.capitalize(), set()).update(capitalized)
    return lexicon


def diocese_entries(expansions) -> list[tuple[str, str, str]]:
    """
    (Auflösung, Wortstamm, Deklination) triples for the diocese adjectives
    (dioceses.csv has no morphology columns): -is words are i-declension
    adjectives (Bremensis), -us words o/a-declension (Tridentinus).
    """
    entries = []
    for word in expansions:
        if word.endswith("is"):
            entries.append((word, f"{word[:-2]} -is", "i (Adj.)"))
        elif word.endswith("us"):
            entries.append((word, f"{word[:-2]} -i", "o/a (Adj.)"))
    return entries


def find_lexicon_occurrences(
    text: str, lexicon: dict[str, set[str]], spans: list[tuple[int, int]] | None = None
) -> list[Occurrence]:
    """
    Occurrences of lexicon words, numbered left to right. Words directly
    followed by a period are (still unexpanded) abbreviations, not
    dictionary-form insertions, and are skipped. If `spans` (from
    inserted_spans) is given, only words inside them are marked, so words
    that were never abbreviated cannot change.
    """
    allowed = None if spans is None else set(spans)
    occurrences = []
    for m in WORD.finditer(text):
        if m.group(0) not in lexicon:
            continue
        if text[m.end() : m.end() + 1] == ".":
            continue
        if allowed is not None and (m.start(), m.end()) not in allowed:
            continue
        occurrences.append(
            Occurrence(
                id=len(occurrences) + 1,
                abbreviation=m.group(0),
                matched=m.group(0),
                start=m.start(),
                end=m.end(),
            )
        )
    return occurrences


def ranked_forms(lexicon: dict[str, set[str]], vocabulary=None) -> dict[str, list[str]]:
    """
    The candidate lists for the prompt: each word's paradigm as a list,
    ranked by corpus frequency (ties alphabetical) if a vocabulary (an
    object with a `counts` Counter, e.g. expand_rest.Vocabulary) is given.
    Forms the model has seen used correctly in the corpus come first.
    """
    if vocabulary is None:
        return {word: sorted(forms) for word, forms in lexicon.items()}
    return {
        word: sorted(forms, key=lambda form: (-vocabulary.counts[form], form))
        for word, forms in lexicon.items()
    }


def build_user_prompt(
    text: str, occurrences: list[Occurrence], candidates: dict[str, list[str]]
) -> str:
    marked = mark_text(text, occurrences)

    lines = [
        "Here is the Latin text with the words to check marked as [[id|word]]:",
        "```",
        marked,
        "```",
        "",
        "The acceptable forms of each marked word (most frequent first):",
    ]
    for occ in occurrences:
        forms = ", ".join(f"`{f}`" for f in candidates[occ.abbreviation])
        lines.append(f"- [[{occ.id}]] `{occ.matched}`: {forms}")
    lines += [
        "",
        "Return a JSON object mapping every id to the form that fits its context"
        " (the current form if it is already correct).",
    ]
    return "\n".join(lines)


def parse_forms(
    content: str, occurrences: list[Occurrence], candidates: dict[str, list[str]]
) -> tuple[dict[int, str] | None, list[dict], list[dict]]:
    """
    Parse the model response.

    Returns (choices, details, errors):
    - choices: id -> form to substitute (only ids whose form differs from
      the text; everything else stays as it is)
    - details: one record per id with the outcome tier:
        "changed" (valid form, differs from the text),
        "kept" (the current form was returned),
        "rejected" (not a form of the word), "missing"
    - errors: rejected/missing/unknown ids with messages
    choices is None if no JSON object could be parsed at all.
    """
    start = content.find("{")
    end = content.rfind("}")
    if start == -1 or end < start:
        return None, [], [{"message": "No JSON object found in model response"}]
    try:
        raw = json.loads(content[start : end + 1])
    except json.JSONDecodeError as e:
        return None, [], [{"message": f"Model response is not valid JSON: {e}"}]
    if not isinstance(raw, dict):
        return None, [], [{"message": "Model response is not a JSON object"}]

    choices: dict[int, str] = {}
    details: list[dict] = []
    errors: list[dict] = []

    for occ in occurrences:
        value = raw.get(str(occ.id))
        record = {"id": occ.id, "word": occ.matched, "form": None}
        if value is None:
            record["tier"] = "missing"
            errors.append(
                {
                    "id": occ.id,
                    "message": f"Missing form: nothing returned for [[{occ.id}]] '{occ.matched}'",
                }
            )
        else:
            value = str(value).strip().strip("`")
            if value == occ.matched:
                record["tier"] = "kept"
                record["form"] = value
            elif value in (candidates.get(occ.abbreviation) or []):
                record["tier"] = "changed"
                record["form"] = value
                choices[occ.id] = value
            else:
                record["tier"] = "rejected"
                errors.append(
                    {
                        "id": occ.id,
                        "message": (
                            f"Rejected form: [[{occ.id}]] '{occ.matched}' → '{value}' "
                            f"(not a form of the word)"
                        ),
                    }
                )
        details.append(record)

    known_ids = {str(occ.id) for occ in occurrences}
    for key in raw:
        if str(key) not in known_ids:
            errors.append({"id": key, "message": f"Unknown id: form for '{key}' ignored"})

    return choices, details, errors
